### PR TITLE
Extensive additions and refactoring

### PR DESCRIPTION
**Pull request by cgarrigues**
I have made considerable changes to the code including extensive refactoring.  Suggest you look at my README file to see if you want my changes.

### CODE REVIEW

**Comment by devondragon** [comment]
@cgarrigues,

There are some changes I would love to merge in (launchd instead of cron, keychain instead of plaintext password, etc...).  However the custom field parent task stuff, and the reporter->context name thing, growl dependency, etc.. are all essentially breaking changes for my use case.  I'm also not convinced that the jira-ruby module is the way to go as it seems to have a lot of open issues and very little active development/support, where as the simple http/json stuff is easily maintained by me.

I'm pretty new to github, so I'm not sure what the best way to handle this PR is...  

Thoughts?

**Comment by cgarrigues** [comment]
I'm also new to github, sorry to say.  Between us maybe we can figure it out.

I did a lot of refactoring to get where I am, so it's not obvious just how to get to where both of us would be happy with the code.

I'm thinking that working on my branch to make some of the new dependencies (growl, for example) optional so that it can handle your use case again might be easier than figuring out how to apply the pieces of mine that you like against your code since some of the refactoring was in order to get them to work easily. (some, like launchd, will be easy, others much less so.)

FWIW, I'm also fairly new at ruby, but after N decades of coding, I have a habit of deep diving into new technologies to figure out what's considered the "right" way to do things with my new technologies.

**Comment by devondragon** [comment]
Maybe it makes sense to you keep your fork, for your use case, and if it's okay with you, I will work on manually merging in the commonly desired changes.  It leaves your fork a little bit detached, but might be easiest path forward...

**Comment by cgarrigues** [comment]
Fine with me.

Have fun merging.

**Comment by devondragon** [comment]
Haha I am:)  Quick question, did you have any issues getting the Keychain stuff working?  I'm getting nil back instead of a usable keychain item.  No errors.

**Comment by devondragon** [comment]
Manual feature merging has been done.  I have been unable to get keychain support working correctly, but the rest of it is functioning as expected.  Closing this PR.

**Comment by cgarrigues** [comment]
My version has moved on slightly since then.  I had to use a loaner mac for a short while and that gave me the opportunity to try it w/o the environment fully configured.


  *   better errors if stuff isn’t set up yet (including keychain).  This includes an error that tells you what to do if your keychain isn’t already set up.  For some reason mine was already there when I set it up originally.  I had to figure out how to set it up by hand on my loaner mac.  This is probably your issue.
  *   if Growl isn’t installed, fall back to Notification Center.

Chris



On Nov 16, 2015, at 1:49 PM, Devon Hillard <notifications@github.com<mailto:notifications@github.com>> wrote:


Manual feature merging has been done. I have been unable to get keychain support working correctly, but the rest of it is functioning as expected. Closing this PR.

**Comment by devondragon** [comment]
Chris,

Great!  The new error message totally sorted things out for me. Manually merged.  All good!

**Comment by cgarrigues** [comment]
Excellent.  I’m still not clear why mine was already configured on the other system, but now we know how to make it work for anybody.

When I’ve got time I’ll see if I can get your version and mine closer to each other. I’d like to get to identical code bases at some point.

On Nov 19, 2015, at 6:18 PM, Devon Hillard <notifications@github.com<mailto:notifications@github.com>> wrote:


Chris,

Great! The new error message totally sorted things out for me. Manually merged. All good!

**Pull request closed without merging**
